<?php
/** @var \Magento\Framework\View\Element\Template $block */
$store = $block->getStore();
if ($store) {
    ?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo('Grid Record') ?></caption>
        <thead>
        <tr>
<!--            <th scope="col" class="col id">--><?php //echo ('ID')?><!--</th>-->
            <th scope="col" class="col storename"><?php echo('Store Name') ?></th>
<!--            <th scope="col" class="col image">--><?php //echo ('Image')?><!--</th>-->
            <th scope="col" class="col image"><?php echo('Image') ?></th>
            <th scope="col" class="col address"><?php echo('Address') ?></th>
            <th scope="col" class="col description"><?php echo('Description') ?></th>
            <th scope="col" class="col schedule"><?php echo('Schedule') ?></th>
            <th scope="col" class="col longitude"><?php echo('Longitude') ?></th>
            <th scope="col" class="col latitude"><?php echo('Latitude') ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>

            <td data-th="<?php echo(('Store Name')) ?>" class="col storename">
                <?php echo $store->getName() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Image')) ?>" class="col image">
                <?php
                $path = $block->getMediaUrl() . 'wysiwyg/storecatalog/' . $store->getImage(); ?>
                <img alt="No image available :("
                     src="<?php echo $path?>"
                     onclick="window.open('<?php echo $path?>', '_blank');"
                     width="250"
                     style="cursor:pointer;"
                >
            </td>


            <td data-th="<?php echo(('Address')) ?>" class="col address">
                <?php echo $store->getAddres() ?>
            </td>
            <td data-th="<?php echo(('Description')) ?>" class="col description">
                <?php echo $store->getDesc() ?>
            </td>
            <td data-th="<?php echo(('Schedule')) ?>" class="col schedule">
                <?php echo $store->getWork() ?>
            </td>
            <td data-th="<?php echo(('Longitude')) ?>" class="col longitude">
                <?php echo $store->getLongi() ?>
            </td>
            <td data-th="<?php echo(('Latitude')) ?>" class="col latitude">
                <?php echo $store->getLati() ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php
} ?>
</div>
