<?php
/** @var \Magento\Framework\View\Element\Template $block */
$store = $block->getStore();
if ($store) {
    ?>
<div class="table-wrapper orders-history">
    <table class="data table table-order-items history" id="my-orders-table">
        <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
        <thead>
        <tr>
            <th scope="col" class="col id"><?php echo __('ID') ?></th>
            <th scope="col" class="col storename"><?php echo __('Store Name') ?></th>
            <th scope="col" class="col image"><?php echo __('Image') ?></th>
            <th scope="col" class="col address"><?php echo __('Address') ?></th>
            <th scope="col" class="col description"><?php echo __('Description') ?></th>
            <th scope="col" class="col schedule"><?php echo __('Schedule') ?></th>
            <th scope="col" class="col longitude"><?php echo __('Longitude') ?></th>
            <th scope="col" class="col latitude"><?php echo __('Latitude') ?></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td data-th="<?= $block->escapeHtml(__('ID')) ?>" class="col id">
                <?php echo $store->getId() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Store Name')) ?>" class="col storename">
                <?php echo $store->getName() ?>
            </td>

            <td data-th="<?= $block->escapeHtml(__('Address')) ?>" class="col address">
                <?php echo $store->getAddres() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Description')) ?>" class="col description">
                <?php echo $store->getDesc() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Schedule')) ?>" class="col schedule">
                <?php echo $store->getWork() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Longitude')) ?>" class="col longitude">
                <?php echo $store->getLongi() ?>
            </td>
            <td data-th="<?= $block->escapeHtml(__('Latitude')) ?>" class="col latitude">
                <?php echo $store->getLati() ?>
            </td>
        </tr>
        </tbody>
    </table>
    <?php
} ?>
</div>
